### PR TITLE
feat: Update container redefinition

### PR DESCRIPTION
**Pull request by EdwinBetanc0urt**
## Bug report / Feature
Updates the container redefinition branch with the changes from the develop branch

#### Other relevant information
* Your OS: Linux Mint 19.1 Cinnamon x64. 
* Browser: Mozilla Firefox 88.0.1.
* Node.js version: 12.20.0.
* adempiere-vue version: 4.3.1.

### CODE REVIEW

**Comment by yamelsenih** [comment]
Please redefine the pull request, this has 57 files

**Comment by EdwinBetanc0urt** [comment]
@yamelsenih That's the difference it has from the branch develop, that includes, documentation files, fixes and new features that are in the develop branch but not in the redefinition branch.

**Comment by yamelsenih** [comment]
Please make a rebate in your branch before propose.

Best regards

**Comment by EdwinBetanc0urt** [comment]
this is similar to the PR https://github.com/adempiere/adempiere-vue/pull/881, to keep the redefinition branch up to date with the changes that are in the develop branch.

**Pull request closed without merging**
