### PR TITLE
feat: Add support to sequence tab.

### PR DESCRIPTION
**Pull request by EdwinBetanc0urt**
Greetings, with this pull request support is added to the tabs of the sequence type, as visualized in the image the order is managed with drag and drop, and changes are sent to the server by pressing the confirm button, automatically updating the list of records associated with this tab.

Peek 27-11-2019 17-03

#111

### CODE REVIEW

**Comment by yamelsenih** [comment]
This does not populate data on first request:
Current ogv

**Comment by EdwinBetanc0urt** [comment]
Greetings @yamelsenih this commit https://github.com/adempiere/adempiere-vue/pull/186/commits/e4eee14f0bf950f0cbb3da619cc6fda54914ebe7 corrects that behavior, as the data is visualized in the first load of data

Peek 03-12-2019 16-36

**Comment by yamelsenih** [comment]
No refresh it:
Current ogv

**Comment by EdwinBetanc0urt** [comment]
Correct multiple petition if parent record has not changed https://github.com/adempiere/adempiere-vue/pull/186/commits/378186c348388b8dcd1dcdcb996f6af62935312f
Peek 03-12-2019 17-55

**Comment by yamelsenih** [comment]
Please @EdwinBetanc0urt resolve this problem with order, note that exists four records with same sequence 10 and 80
Current ogv

**Comment by EdwinBetanc0urt** [comment]
Greetings @yamelsenih , corrected the error, also added the display of the value the order column according to each record enabled in the sequence. It was not added in those that are not added for the sequence since it must be understood that it takes the value of zero.

Peek 10-12-2019 15-40

**Pull request merged**
