### PR TITLE
Add calculator component to numeric references

### PR DESCRIPTION
**Pull request by leonel1524**
**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactor
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [x] It's submitted to the `develop` branch, not the `master` branch
- [x] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). Don't request your `master` branch!
- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)

If adding a **new feature**, the PR's description includes:
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

## Description
Hello everyone, in this PR a calculator component is added for fields that are numerical type.

### Screenshots

 **Before this PR**
numeric
**After this PR**
calc-component

### CODE REVIEW

**Comment by yamelsenih** [comment]
Please resolve conflicts
Also is nice to have up display instead down, see:

Screenshot_20200222_235951

Also is better if you add math opetarions for fields when they are numerics

**Comment by EdwinBetanc0urt** [comment]
The conflicts were resolved and the input values for the calculator were changed to the top

Peek 24-02-2020 15-07

In addition, if a field has a value, when the calculator is displayed, the value of the field is set in the calculator

**Comment by yamelsenih** [comment]
Hey guy please add a span for buttons

**Comment by leonel1524** [comment]
Styles changed
image

**Comment by yamelsenih** [comment]
Hi @leonel1524 have you a mathematical operation directly from field instead open calculator?

**Comment by leonel1524** [comment]
Updated! Now perform the calculation in real time and show a tooltip with the partial result, when blurring the field is updated.

calc-parenthesis

**Pull request merged**
