### PR TITLE
Fix Record Access

### PR DESCRIPTION
**Pull request by elsiosanchez**
## Bug report / Feature
Fix Record Access 
### Before Pull Request
cal

### After Pull Request
cal

#### Other relevant information
- Your OS: Debian 9
- Web Browser: Chrome
- Node.js version: 10.9

#### Additional context
Error in mobile mode when opening Record Access displays the modal and the panel on the right.

### CODE REVIEW

**Comment by oscarinak** [comment]
The pull verification was carried out and the following observations are presented:

-When going from desktop mode to mobile mode, the modal sale of "Registration Access" is not maintained to become a panel that is displayed on the right of the mobile view.

- Being in mobile mode and checking the "Access to Registry" option, ADempiere presents slowness to display the panel on the right.

- The only thing that is fulfilled with the revision is that being in mobile mode when checking the "Access to Registry" option it no longer scrolls as a modal window, if not as a panel on the right but slowly


Verificacion_pullR_832

**Comment by oscarinak** [comment]
Good but with observations

**Comment by elsiosanchez** [comment]
> Good but with observations

Correct Observation

**Comment by oscarinak** [comment]
The review of the pr was carried out and it complies with the indicated:

-It complies that when changing from desktop mode to mobile, the view of the registration access is maintained and this when changing to mobile mode is positioned on the right side

Verificación_ParteII_PullR_832_Bueno

**Comment by oscarinak** [comment]
Good

**Pull request merged**
