### PR TITLE
add ADempiere template to make components, views and store modules files

### PR DESCRIPTION
**Pull request by leonel1524**
**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactor
- [ ] Build-related changes
- [ ] Documentation content changes
- [x] Other, please describe: File templates.

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [x] It's submitted to the `develop` branch, not the `master` branch
- [x] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). Don't request your `master` branch!
- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)

## Description
Hello everyone, in this PR has been added new plop templates for make easy new Components, Store Modules and Views files in ADempiere vue. 

### Screenshots

 **Before this PR**
Screenshot_20200220_162254

**After this PR**
Screenshot_20200220_162200

### CODE REVIEW

**Comment by EdwinBetanc0urt** [comment]
@leonel1524 Please show output code of the templates.

**Comment by yamelsenih** [comment]
Can you add a example of code?

**Comment by EdwinBetanc0urt** [comment]
## Output code for templates
```Shell
cd path/to/adempiere-vue
npm run new
```
**View Template**
Name: Test
Path: `./src/views/ADempiere/Test/index.vue`
Code output:
```vue
<template>
  <div />
</template>

<script>
export default {
  name: 'Test',
  props: {},
  data() {
    return {}
  },
  created() {},
  mounted() {},
  methods: {}
}
</script>

<style lang="scss" scoped>

</style>

```


**Component Template**
Name: TestComponent
Path: `./src/components/ADempiere/TestComponent/index.vue`
```vue
<template>
  <div />
</template>

<script>
export default {
  name: 'TestComponent',
  props: {},
  data() {
    return {}
  },
  created() {},
  mounted() {},
  methods: {}
}
</script>

<style lang="scss" scoped>

</style>

```


**Store Module Template**
Name: test
Path: `./src/store/modules/ADempiere/test.js`
```javascript
const test = {
  state: {
    test: {}
  },
  mutations: {},
  actions: {},
  getters: {
    gettest: (state) => {
      return state.test
    }
  }
}

export default test

```

**Comment by yamelsenih** [comment]
Please describe each command

**Pull request merged**
