### PR TITLE
Correction of the style in the button "new order"

### PR DESCRIPTION
**Pull request by Andojeda**
## Bug / Feature Report

Distortion of the "new order" button in the point of sale window, when the catalog and options panels are opened.

### Steps to reproduce the style correction in "new order" button

1. Enter the point of sale.
2. Open the catalog panel.

#### Screenshot or GIF
fix

#### Expected behavior
The "new order" button does not move position when opening the catalog panel.

### CODE REVIEW

**Comment by yamelsenih** [comment]
Please split this PR.
1- Translation
2- Style

**Comment by EdwinBetanc0urt** [comment]
this is similar to the PR https://github.com/adempiere/adempiere-vue/pull/881, to keep the redefinition branch up to date with the changes that are in the develop branch.

**Comment by EdwinBetanc0urt** [comment]
this is similar to the PR https://github.com/adempiere/adempiere-vue/pull/881, to keep the redefinition branch up to date with the changes that are in the develop branch.

**Comment by Andojeda** [comment]
PR has already been fixed

**Comment by oscarinak** [comment]
The PR verification was carried out in the following service "https://deploy-preview-896--stoic-lamport-68decf.netlify.app/#/" where it complies with those described which when opening the product catalog in the point of sale, the button that indicates "New Records" maintain the same position at the point of sale

Verificación_PR_896

**Comment by oscarinak** [comment]
Good

**Pull request merged**
