### PR TITLE
Add Change Log option in field

### PR DESCRIPTION
**Pull request by elsiosanchez**
##  Feature

Add Change Log option in field
#### Screenshot or Gif
cal

### CODE REVIEW

**Comment by yamelsenih** [comment]
Hi @elsiosanchez this not worked for mobile ui

**Comment by elsiosanchez** [comment]
Hello @yamelsenih this was already supported for mobile mode

cal

**Comment by yamelsenih** [comment]
Green: who is the author?
Red: where is the scroll?
IMG_20210506_230142

**Comment by elsiosanchez** [comment]
Add who is the author
Add where is the scroll

cal

**Comment by yamelsenih** [comment]
I don't sure if is good hide the change log because each user change is visible only when the user make click over component and is very bad it. Please try add a component that can show all changes wuthout more clicks

**Comment by elsiosanchez** [comment]
image

**Comment by oscarinak** [comment]
The verification was carried out and it complies with the established, however the view from where the history of the field comes out is not a pleasant sight and sometimes it comes out halfway

Verificación_pull822

**Comment by oscarinak** [comment]
Good

**Pull request merged**
