### PR TITLE
fix: Load Smart Browser.

### LINKED ISSUE #99: Support for ADempiere SmartBrowser
hello, it is necessary to migrate ADempiere Smart Browser to the Javascript Reactive Framework [Vue.js](https://vuejs.org/) and [Element-UI.](https://element.eleme.cn/2.7/#/en-US)

- **ADempiere**
zkbrowser

- **ADempiere-Vue**
browservue

- **ADempiere-Vue(mobile)**
mobilbrowser

### PR DESCRIPTION
**Pull request by EdwinBetanc0urt**
#### Steps to reproduce

1. Open SB without process asociate (Request Browser).

#### Screenshot or Gif

Before this PR:
browser-loaded-error

After this PR:
https://user-images.githubusercontent.com/20288327/120058002-94e7d680-c015-11eb-8bb1-ce6c761bc262.mp4

#### Expected behavior
The smart browser is expected to open correctly.

#### Other relevant information
* Your OS: Linux Mint 19.1 Cinnamon x64. 
* Browser: Mozilla Firefox 88.0.1.
* Node.js version: 12.20.0.
* adempiere-vue version: 4.3.1.

#### Additional context
Depends on https://github.com/adempiere/gRPC-API/pull/4
Depends on https://github.com/adempiere/proxy-adempiere-api/pull/25

closes https://github.com/adempiere/adempiere-vue/issues/99

### CODE REVIEW

**Comment by oscarinak** [comment]
The PR verification was carried out in the following service "https://deploy-preview-889--stoic-lamport-68decf.netlify.app/" where the following observations were found:

- When opening the SB it keeps throwing the same error
-It was tried to open a second time and this one showed its view from ADempiere however it threw some error messages, which can be seen in the following Gif

Verificación_PullR_889

**Comment by oscarinak** [comment]
bad

**Comment by EdwinBetanc0urt** [comment]
@oscarinak For the tests to take effect, the following changes must first be approved and mounted on the demo server
- adempiere/gRPC-API#4
- adempiere/proxy-adempiere-api#25

@yamelsenih please check the above mentioned PRs.

**Comment by oscarinak** [comment]
The review was performed again and the error persists

image

**Pull request merged**
