### PR TITLE
feat: Panel redefinition

### PR DESCRIPTION
**Pull request by EdwinBetanc0urt**
## Bug report / Feature
The field panel is redefined to separate the logics and what it should do according to the guy.

Currently the field panel is very extensive and with multiple conditions to act according to the way, but it makes the support difficult and adding new functionalities leads in most cases to break the operability.

#### Steps to reproduce

1. Open a Process/Report with fields.

#### Screenshot or Gif
Captura de pantalla de 2021-05-22 07-32-52

#### Other relevant information
- Your OS: Linux Mint 19.1 Cinnamon x64.
- Web Browser: Mozilla Firefox 85.0.
- Node.js version: 12.20.0.
- adempiere-vue version: 4.3.1.

#### Additional context
The vue 2 composition api is used for the use of new components and the Report/Process view component is redesigned.

### CODE REVIEW

**Comment by yamelsenih** [comment]
Please put a comment about this change

**Comment by yamelsenih** [comment]
Hi @EdwinBetanc0urt please consider create a fresh branch for upload only specific changes. 50 files is very too long for review
IMG_20210525_204153

**Comment by EdwinBetanc0urt** [comment]
@yamelsenih The difference is because it is pointing to the test branch that you told me feature/container-redefinition, you should update it to develop but you don't see the netlify CI, or I should point it directly to develop and it will show the netlify CI.

Please see that there are 27 files in the following link if compared against the branch develop https://github.com/adempiere/adempiere-vue/compare/develop...EdwinBetanc0urt:feature/panel-definition

compare

**Comment by yamelsenih** [comment]
Ok let me update first. Thanks

**Comment by EdwinBetanc0urt** [comment]
this PR closes in favor of https://github.com/adempiere/adempiere-vue/pull/875

**Pull request closed without merging**
